version: "3.8"

services:
  # sql:
  #   container_name: sqlserver
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   ports:
  #     - 1433:1433
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: "5tYuqs12#$"
  #   networks:
  #     - aspcore-network
  netcore:
    container_name: RecipeRecollection
    build: 
      context: .
      dockerfile: ./RecipeRecollection/Dockerfile
    # image: masonbair/recipe-recollection:webApp
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - 8080:80
    networks:
      - aspcore-network
    # depends_on:
    #   - sql

networks:
    aspcore-network:
        driver: bridge